#!/bin/bash
set -e

PKG_DIR=python2
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR     ###### Getting source

PACKAGE=Python-2.7.13.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/p/$PACKAGE
  fi
fi
echo "53b43534153bb2a0363f08bae8b9d990  $PACKAGE" | md5sum -c -

PACKAGE1=python-2.7.13-docs-html.tar.bz2
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://docs.python.org/2.7/archives/python-2.7.13-docs-html.tar.bz2 ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/p/$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR


cd $BUILD_DIR        ##### Unpacking source
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
#######  Building package
cd $UNPACKDIR

./configure --prefix=/usr       \
            --enable-shared     \
            --with-system-expat \
            --with-system-ffi   \
            --with-ensurepip=yes \
            --enable-unicode=ucs4 &&
make
#make -k test || true
sudo -E sh << ROOT_EOF
make -j1 install &&
chmod -v 755 /usr/lib/libpython2.7.so.1.0
ROOT_EOF
sudo -E sh << ROOT_EOF
install -v -dm755 /usr/share/doc/python-2.7.13 &&

tar --strip-components=1                     \\
    --no-same-owner                          \\
    --directory /usr/share/doc/python-2.7.13 \\
    -xvf ../python-2.7.13-docs-html.tar.bz2 &&

find /usr/share/doc/python-2.7.13 -type d -exec chmod 0755 {} \\; &&
find /usr/share/doc/python-2.7.13 -type f -exec chmod 0644 {} \\;
ROOT_EOF
sudo /sbin/ldconfig

sudo -E sh << ROOT_EOF
export PYTHONDOCS=/usr/share/doc/python-2.7.13
ROOT_EOF

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit