#!/bin/bash
set -e

PKG_DIR=gtk3
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR     ###### Getting source

PACKAGE=gtk+-3.22.18.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 http://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.18.tar.xz ||
    wget -T 30 -t 5 ftp://ftp.gnome.org/pub/gnome/sources/gtk+/3.22/gtk+-3.22.18.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/g/$PACKAGE
  fi
fi
echo "5c574a872ef3af67706bd612374ea58b  $PACKAGE" | md5sum -c -


cd $BUILD_DIR        ##### Unpacking source
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
#######  Building package
cd $UNPACKDIR

./configure --prefix=/usr             \
            --sysconfdir=/etc         \
            --enable-broadway-backend \
            --enable-x11-backend      \
            --disable-wayland-backend &&
make
#make -k check || true
sudo -E sh << ROOT_EOF
make -j1 install
ROOT_EOF
sudo -E sh << ROOT_EOF
gtk-query-immodules-3.0 --update-cache
ROOT_EOF
sudo -E sh << ROOT_EOF
glib-compile-schemas /usr/share/glib-2.0/schemas
ROOT_EOF
sudo /sbin/ldconfig

mkdir -vp ~/.config/gtk-3.0
cat > ~/.config/gtk-3.0/settings.ini << "EOF"
[Settings]
gtk-theme-name = **EDITMEAdwaitaEDITME**
gtk-icon-theme-name = **EDITMEoxygenEDITME**
gtk-font-name = **EDITMEDejaVu Sans 12EDITME**
gtk-cursor-theme-size = **EDITME18EDITME**
gtk-toolbar-style = **EDITMEGTK_TOOLBAR_BOTH_HORIZEDITME**
gtk-xft-antialias = **EDITME1EDITME**
gtk-xft-hinting = **EDITME1EDITME**
gtk-xft-hintstyle = **EDITMEhintslightEDITME**
gtk-xft-rgba = **EDITMErgbEDITME**
gtk-cursor-theme-name = **EDITMEAdwaitaEDITME**
EOF

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit