#!/bin/bash
set -e

PKG_DIR=zsh
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR     ###### Getting source

PACKAGE=zsh-5.4.2.tar.gz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 http://www.zsh.org/pub/zsh-5.4.2.tar.gz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/z/$PACKAGE
  fi
fi
echo "dfe156fd69b0d8d1745ecf6d6e02e047  $PACKAGE" | md5sum -c -

PACKAGE1=zsh-5.4.2-doc.tar.xz
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 http://www.zsh.org/pub/zsh-5.4.2-doc.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/z/$PACKAGE1
  fi
fi
echo "e718bbcd663992ba33c01d4f8a289fc5  $PACKAGE1" | md5sum -c -
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR


cd $BUILD_DIR        ##### Unpacking source
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
#######  Building package
cd $UNPACKDIR

tar --strip-components=1 -xvf ../zsh-5.4.2-doc.tar.xz
./configure --prefix=/usr         \
            --bindir=/bin         \
            --sysconfdir=/etc/zsh \
            --enable-etcdir=/etc/zsh                  &&
make                                                  &&

makeinfo  Doc/zsh.texi --plaintext -o Doc/zsh.txt     &&
makeinfo  Doc/zsh.texi --html      -o Doc/html        &&
makeinfo  Doc/zsh.texi --html --no-split --no-headers -o Doc/zsh.html
texi2pdf  Doc/zsh.texi -o Doc/zsh.pdf
#make -k check || true
sudo -E sh << ROOT_EOF
make -j1 install                              &&
make -j1 infodir=/usr/share/info install.info &&

install -v -m755 -d                 /usr/share/doc/zsh-5.4.2/html &&
install -v -m644 Doc/html/*         /usr/share/doc/zsh-5.4.2/html &&
install -v -m644 Doc/zsh.{html,txt} /usr/share/doc/zsh-5.4.2
ROOT_EOF
sudo -E sh << ROOT_EOF
make -j1 htmldir=/usr/share/doc/zsh-5.4.2/html install.html &&
install -v -m644 Doc/zsh.dvi /usr/share/doc/zsh-5.4.2
ROOT_EOF
sudo -E sh << ROOT_EOF
install -v -m644 Doc/zsh.pdf /usr/share/doc/zsh-5.4.2
ROOT_EOF
sudo /sbin/ldconfig

sudo -E sh << ROOT_EOF
cat >> /etc/shells << "EOF"
/bin/zsh
EOF
ROOT_EOF

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit