#!/bin/bash
set -e

PKG_DIR=poppler
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR     ###### Getting source

PACKAGE=poppler-0.57.0.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://poppler.freedesktop.org/poppler-0.57.0.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/p/$PACKAGE
  fi
fi
echo "bc5a191741604552c90d484103229374  $PACKAGE" | md5sum -c -

PACKAGE1=poppler-data-0.4.8.tar.gz
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://poppler.freedesktop.org/poppler-data-0.4.8.tar.gz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/p/$PACKAGE1
  fi
fi
echo "00f8989c804de84af0ba2ea629949980  $PACKAGE1" | md5sum -c -
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR


cd $BUILD_DIR        ##### Unpacking source
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
#######  Building package
cd $UNPACKDIR

./configure --prefix=/usr               \
            --sysconfdir=/etc           \
            --disable-static            \
            --enable-build-type=release \
            --enable-cmyk               \
            --enable-xpdf-headers       \
            --with-testdatadir=$PWD/testfiles &&
make
#make -k  || true
#LC_ALL=en_US.UTF-8 make -k check || true
sudo -E sh << ROOT_EOF
make -j1 install
ROOT_EOF
sudo -E sh << ROOT_EOF
install -v -m755 -d        /usr/share/doc/poppler-0.57.0 &&
install -v -m644 README*   /usr/share/doc/poppler-0.57.0 &&
cp -vr glib/reference/html /usr/share/doc/poppler-0.57.0
ROOT_EOF
tar -xf ../poppler-data-0.4.8.tar.gz &&
cd poppler-data-0.4.8
sudo -E sh << ROOT_EOF
make -j1 prefix=/usr install
ROOT_EOF
sudo /sbin/ldconfig

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit