#!/bin/bash
set -e

PKG_DIR=tcl
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR     ###### Getting source

PACKAGE=tcl8.6.7-src.tar.gz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://downloads.sourceforge.net/tcl/tcl8.6.7-src.tar.gz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/t/$PACKAGE
  fi
fi
echo "5673aaf45b5de5d8dd80bb3daaeb8838  $PACKAGE" | md5sum -c -

PACKAGE1=tcl8.6.7-html.tar.gz
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://downloads.sourceforge.net/tcl/tcl8.6.7-html.tar.gz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/t/$PACKAGE1
  fi
fi
echo "0da678eaf3041346030898c23c14e97e  $PACKAGE1" | md5sum -c -
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR


cd $BUILD_DIR        ##### Unpacking source
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
#######  Building package
cd $UNPACKDIR

tar -xf ../tcl8.6.7-html.tar.gz --strip-components=1
export SRCDIR=`pwd` &&

cd unix &&

./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            $([ $(uname -m) = x86_64 ] && echo --enable-64bit) &&
make &&

sed -e "s#$SRCDIR/unix#/usr/lib#" \
    -e "s#$SRCDIR#/usr/include#"  \
    -i tclConfig.sh               &&

sed -e "s#$SRCDIR/unix/pkgs/tdbc1.0.5#/usr/lib/tdbc1.0.5#" \
    -e "s#$SRCDIR/pkgs/tdbc1.0.5/generic#/usr/include#"    \
    -e "s#$SRCDIR/pkgs/tdbc1.0.5/library#/usr/lib/tcl8.6#" \
    -e "s#$SRCDIR/pkgs/tdbc1.0.5#/usr/include#"            \
    -i pkgs/tdbc1.0.5/tdbcConfig.sh                        &&

sed -e "s#$SRCDIR/unix/pkgs/itcl4.1.0#/usr/lib/itcl4.1.0#" \
    -e "s#$SRCDIR/pkgs/itcl4.1.0/generic#/usr/include#"    \
    -e "s#$SRCDIR/pkgs/itcl4.1.0#/usr/include#"            \
    -i pkgs/itcl4.1.0/itclConfig.sh                        &&

unset SRCDIR
#make -k test || true
sudo -E sh << ROOT_EOF
make -j1 install &&
make -j1 install-private-headers &&
ln -v -sf tclsh8.6 /usr/bin/tclsh &&
chmod -v 755 /usr/lib/libtcl8.6.so
ROOT_EOF
sudo -E sh << ROOT_EOF
mkdir -v -p /usr/share/doc/tcl-8.6.7 &&
cp -v -r  ../html/* /usr/share/doc/tcl-8.6.7
ROOT_EOF
sudo /sbin/ldconfig

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit