#!/bin/bash
set -e

PKG_DIR=git
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR     ###### Getting source

PACKAGE=git-2.14.1.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://www.kernel.org/pub/software/scm/git/git-2.14.1.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/g/$PACKAGE
  fi
fi
echo "a55bc6a2164d3ef1c3e5fc2f0c1d0d52  $PACKAGE" | md5sum -c -

PACKAGE1=git-manpages-2.14.1.tar.xz
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://www.kernel.org/pub/software/scm/git/git-manpages-2.14.1.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/g/$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR

PACKAGE1=git-htmldocs-2.14.1.tar.xz
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.14.1.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/g/$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR


cd $BUILD_DIR        ##### Unpacking source
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
#######  Building package
cd $UNPACKDIR

./configure --prefix=/usr --with-gitconfig=/etc/gitconfig &&
make
make html
make man
#make -k test || true
sudo -E sh << ROOT_EOF
make -j1 install
ROOT_EOF
sudo -E sh << ROOT_EOF
make -j1 install-man
ROOT_EOF
sudo -E sh << ROOT_EOF
make -j1 htmldir=/usr/share/doc/git-2.14.1 install-html
ROOT_EOF
sudo -E sh << ROOT_EOF
tar -xf ../git-manpages-2.14.1.tar.xz \\
    -C /usr/share/man --no-same-owner --no-overwrite-dir
ROOT_EOF
sudo -E sh << ROOT_EOF
mkdir -vp   /usr/share/doc/git-2.14.1 &&
tar   -xf   ../git-htmldocs-2.14.1.tar.xz \\
      -C    /usr/share/doc/git-2.14.1 --no-same-owner --no-overwrite-dir &&

find        /usr/share/doc/git-2.14.1 -type d -exec chmod 755 {} \\; &&
find        /usr/share/doc/git-2.14.1 -type f -exec chmod 644 {} \\;
ROOT_EOF
sudo -E sh << ROOT_EOF
mkdir -vp /usr/share/doc/git-2.14.1/man-pages/{html,text}         &&
mv        /usr/share/doc/git-2.14.1/{git*.txt,man-pages/text}     &&
mv        /usr/share/doc/git-2.14.1/{git*.,index.,man-pages/}html &&

mkdir -vp /usr/share/doc/git-2.14.1/technical/{html,text}         &&
mv        /usr/share/doc/git-2.14.1/technical/{*.txt,text}        &&
mv        /usr/share/doc/git-2.14.1/technical/{*.,}html           &&

mkdir -vp /usr/share/doc/git-2.14.1/howto/{html,text}             &&
mv        /usr/share/doc/git-2.14.1/howto/{*.txt,text}            &&
mv        /usr/share/doc/git-2.14.1/howto/{*.,}html               &&

sed -i '/^<a href=/s|howto/|&html/|' /usr/share/doc/git-2.14.1/howto-index.html &&
sed -i '/^\\* link:/s|howto/|&html/|' /usr/share/doc/git-2.14.1/howto-index.txt
ROOT_EOF
sudo /sbin/ldconfig

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit