#!/bin/bash
set -e

PKG_DIR=wireshark
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR     ###### Getting source

PACKAGE=wireshark-2.4.0.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 https://www.wireshark.org/download/src/all-versions/wireshark-2.4.0.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/w/$PACKAGE
  fi
fi
echo "655106f8cf3bb8f521336d3a8ab5b10b  $PACKAGE" | md5sum -c -

PATCH=wireshark-2.4.0-lua_5_3-1.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $SRC_ARCHIVE/$PATCH ]] ; then
    cp $SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/8.1/wireshark-2.4.0-lua_5_3-1.patch ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/w/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR

PACKAGE1=
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://www.wireshark.org/download/docs/ ||
    wget -T 30 -t 5 ${FTP_SERVER}svn//$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR


cd $BUILD_DIR        ##### Unpacking source
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
#######  Building package
cd $UNPACKDIR

sudo -E sh << ROOT_EOF
groupadd -g 62 wireshark
ROOT_EOF
patch -Np1 -i ../wireshark-2.4.0-lua_5_3-1.patch  &&

./configure --prefix=/usr --sysconfdir=/etc &&
make
sudo -E sh << ROOT_EOF
make -j1 install &&

install -v -m755 -d /usr/share/doc/wireshark-2.4.0 &&
install -v -m644    README{,.linux} doc/README.* doc/*.{pod,txt} \\
                    /usr/share/doc/wireshark-2.4.0 &&

pushd /usr/share/doc/wireshark-2.4.0 &&
   for FILENAME in ../../wireshark/*.html; do
      ln -s -v -f \$FILENAME .
   done &&
popd
unset FILENAME
ROOT_EOF
sudo -E sh << ROOT_EOF
install -v -m644 **EDITME<Downloaded_Files>EDITME** \\
                 /usr/share/doc/wireshark-2.4.0
ROOT_EOF
sudo -E sh << ROOT_EOF
chown -v root:wireshark /usr/bin/{tshark,dumpcap} &&
chmod -v 6550 /usr/bin/{tshark,dumpcap}
ROOT_EOF
sudo -E sh << ROOT_EOF
usermod -a -G wireshark <username>
ROOT_EOF
sudo /sbin/ldconfig

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit