#!/bin/bash
set -e

export LXQT_PREFIX=/usr
sudo -E sh << ROOT_EOF
cat > /etc/profile.d/lxqt.sh << "EOF"
# Begin LXQt profile

export LXQT_PREFIX=/usr

# End LXQt profile
EOF
ROOT_EOF
sudo -E sh << ROOT_EOF
install -vdm755 /opt/lxqt/{bin,lib,share/man}

cat > /etc/profile.d/lxqt.sh << "EOF"
# Begin LXQt profile

export LXQT_PREFIX=/opt/lxqt

pathappend /opt/lxqt/bin           PATH
pathappend /opt/lxqt/share/man/    MANPATH
pathappend /opt/lxqt/lib/pkgconfig PKG_CONFIG_PATH
pathappend /opt/lxqt/lib/plugins   QT_PLUGIN_PATH

# End LXQt profile
EOF

cat >> /etc/profile.d/qt5.sh << "EOF"

# Begin Qt5 changes for LXQt

pathappend \$QT5DIR/plugins         QT_PLUGIN_PATH

# End Qt5 changes for LXQt
EOF
ROOT_EOF
sudo -E sh << ROOT_EOF
cat >> /etc/ld.so.conf << "EOF"

# Begin LXQt addition

/opt/lxqt/lib

# End LXQt addition

EOF
ROOT_EOF
source /etc/profile
sudo -E sh << ROOT_EOF
source /etc/profile                                       &&
install -v -dm755                \$LXQT_PREFIX/share/icons &&
ln -sfv /usr/share/icons/hicolor \$LXQT_PREFIX/share/icons &&
ln -sfv /usr/share/dbus-1        \$LXQT_PREFIX/share 
ROOT_EOF
sudo -E sh << ROOT_EOF
mv /opt/lxqt{,-0.11.1}
ln -sfv lxqt-0.11.1 /opt/lxqt
ROOT_EOF
exit