#!/bin/bash
set -e

PKG_DIR=mplayer
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR     ###### Getting source

PACKAGE=MPlayer-1.3.0.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 http://www.mplayerhq.hu/MPlayer/releases/MPlayer-1.3.0.tar.xz ||
    wget -T 30 -t 5 ftp://ftp.mplayerhq.hu/MPlayer/releases/MPlayer-1.3.0.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/m/$PACKAGE
  fi
fi
echo "e8a4d77ad4f509e81dd5e13b51636c1d  $PACKAGE" | md5sum -c -

PACKAGE1=Clearlooks-1.7.tar.bz2
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://www.mplayerhq.hu/MPlayer/skins/Clearlooks-1.7.tar.bz2 ||
    wget -T 30 -t 5 ftp://ftp.mplayerhq.hu/MPlayer/skins/Clearlooks-1.7.tar.bz2 ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/c/$PACKAGE1
  fi
fi
echo "833d82734deb8475a8c57e9c1b55bd86  $PACKAGE1" | md5sum -c -
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR

PACKAGE1=
if [[ ! -f $PACKAGE1 ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE1 ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE1 $PACKAGE1
  else
    wget -T 30 -t 5 https://www.mplayerhq.hu/MPlayer/skins/ ||
    wget -T 30 -t 5 ${FTP_SERVER}svn//$PACKAGE1
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PACKAGE1 $BUILD_DIR


cd $BUILD_DIR        ##### Unpacking source
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
#######  Building package
cd $UNPACKDIR

./configure --prefix=/usr            \
            --confdir=/etc/mplayer   \
            --enable-dynamic-plugins \
            --enable-menu            \
            --enable-gui             &&
make
make doc
sudo -E sh << ROOT_EOF
make -j1 install  &&
ln -svf ../icons/hicolor/48x48/apps/mplayer.png \\
        /usr/share/pixmaps/mplayer.png
ROOT_EOF
sudo -E sh << ROOT_EOF
install -v -m755 -d /usr/share/doc/mplayer-1.3.0 &&
install -v -m644    DOCS/HTML/en/* \\
                    /usr/share/doc/mplayer-1.3.0
ROOT_EOF
sudo -E sh << ROOT_EOF
install -v -m644 etc/codecs.conf /etc/mplayer
ROOT_EOF
sudo -E sh << ROOT_EOF
install -v -m644 etc/*.conf /etc/mplayer
ROOT_EOF
sudo -E sh << ROOT_EOF
gtk-update-icon-cache &&
update-desktop-database
ROOT_EOF
sudo -E sh << ROOT_EOF
tar -xvf  ../Clearlooks-1.7.tar.bz2 \\
    -C    /usr/share/mplayer/skins &&
ln  -sfvn Clearlooks /usr/share/mplayer/skins/default
ROOT_EOF
sudo /sbin/ldconfig

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit