#!/bin/bash
set -e

PKG_DIR=glib2
SRC_DIR=${SRC_ARCHIVE}${SRC_SUBDIRS:+/${PKG_DIR}}
BUILD_DIR=${BUILD_ROOT}${BUILD_SUBDIRS:+/${PKG_DIR}}
mkdir -p $SRC_DIR
mkdir -p $BUILD_DIR

cd $SRC_DIR

PACKAGE=glib-2.54.2.tar.xz
if [[ ! -f $PACKAGE ]] ; then
  if [[ -f $SRC_ARCHIVE/$PACKAGE ]] ; then
    cp $SRC_ARCHIVE/$PACKAGE $PACKAGE
  else
    wget -T 30 -t 5 http://ftp.gnome.org/pub/gnome/sources/glib/2.54/glib-2.54.2.tar.xz ||
    wget -T 30 -t 5 ftp://ftp.gnome.org/pub/gnome/sources/glib/2.54/glib-2.54.2.tar.xz ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/g/$PACKAGE
  fi
fi
echo "50f83e08f080f99b1e2f0ad2b760fb81  $PACKAGE" | md5sum -c -

PATCH=glib-2.54.2-meson_fixes-1.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $SRC_ARCHIVE/$PATCH ]] ; then
    cp $SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/svn/glib-2.54.2-meson_fixes-1.patch ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/g/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR

PATCH=glib-2.54.2-skip_warnings-1.patch
if [[ ! -f $PATCH ]] ; then
  if [[ -f $SRC_ARCHIVE/$PATCH ]] ; then
    cp $SRC_ARCHIVE/$PATCH $PATCH
  else
    wget -T 30 -t 5 http://www.linuxfromscratch.org/patches/blfs/svn/glib-2.54.2-skip_warnings-1.patch ||
    wget -T 30 -t 5 ${FTP_SERVER}svn/g/$PATCH
  fi
fi
[[ "$SRC_DIR" != "$BUILD_DIR" ]] && ln -sf $SRC_DIR/$PATCH $BUILD_DIR


cd $BUILD_DIR
find . -maxdepth 1 -mindepth 1 -type d | xargs sudo rm -rf
case $PACKAGE in
  *.tar.gz|*.tar.bz2|*.tar.xz|*.tgz|*.tar.lzma)
     tar -xvf $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR=`grep '[^./]\+' unpacked | head -n1 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.tar.lz)
     bsdtar -xvf $SRC_DIR/$PACKAGE 2> unpacked
     UNPACKDIR=`head -n1 unpacked | cut  -d" " -f2 | sed 's@^\./@@;s@/.*@@'`
     ;;
  *.zip)
     zipinfo -1 $SRC_DIR/$PACKAGE > unpacked
     UNPACKDIR="$(sed 's@/.*@@' unpacked | uniq )"
     if test $(wc -w <<< $UNPACKDIR) -eq 1; then
       unzip $SRC_DIR/$PACKAGE
     else
       UNPACKDIR=${PACKAGE%.zip}
       unzip -d $UNPACKDIR $SRC_DIR/$PACKAGE
     fi
     ;;
  *)
     UNPACKDIR=$PKG_DIR-build
     mkdir $UNPACKDIR
     cp $SRC_DIR/$PACKAGE $UNPACKDIR
     cp $(find . -mindepth 1 -maxdepth 1 -type l) $UNPACKDIR
     ;;
esac
cd $UNPACKDIR

patch -Np1 -i ../glib-2.54.2-skip_warnings-1.patch
patch -Np1 -i ../glib-2.54.2-meson_fixes-1.patch &&

mkdir build-glib &&
cd    build-glib &&

meson --prefix=/usr -Dwith-pcre=system -Dwith-docs=no .. &&
ninja
sudo -E sh << ROOT_EOF
ninja install &&

chmod -v 755 /usr/bin/{gdbus-codegen,glib-gettextize} &&

mkdir -p /usr/share/doc/glib-2.54.2 &&
cp -r ../docs/reference/{NEWS,README,gio,glib,gobject} /usr/share/doc/glib-2.54.2
ROOT_EOF
#make -k  || true
sudo /sbin/ldconfig

cd $BUILD_DIR
[[ -n "$KEEP_FILES" ]] || sudo rm -rf $UNPACKDIR unpacked

exit